---
hero_image: images / hero-rock-band-large.png
listed: true
copyedit: false
title: रॉक बँड
description: 'आपल्या स्वत: चे वाद्ये कोड (code) करायला शिका'
version: 4.1.1
last_tested: 2018-10-12
steps:
  - 
    title: परिचय
  - 
    title: स्प्राईट्स (Sprites)
  - 
    title: स्टेज
  - 
    title: ड्रम बनविणे
  - 
    title: "आव्हान: आपले ड्रम सुधारित करा"
    challenge: true
  - 
    title: गायक बनविणे
  - 
    title: वेशभूषा
  - 
    title: "आव्हान: आपला बँड (Band) सुधारित करा"
    challenge: true
  - 
    title: Reflection
    quiz: true
  - 
    title: "What next?"


