---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Band Roc
description: Dysga sut i godio offerynnau cerddorol
version: 4.1.1
last_tested: 2018-10-12
steps:
  - 
    title: Cyflwyniad
  - 
    title: Corluniau
  - 
    title: Y Llwyfan
  - 
    title: Creu drwm
  - 
    title: "Her: Perffeithio dy ddrwm"
    challenge: true
  - 
    title: Creu canwr
  - 
    title: Gwisgoedd
  - 
    title: "Her: gwella dy fand"
    challenge: true
  - 
    title: Reflection
    quiz: true
  - 
    title: "What next?"


